###########################################################
### Git Aliases
###########################################################

alias ga='git add'
alias gaa='git add -A'
alias gb='git branch'
alias gba='git branch -a'
alias gbr='git branch -r'
alias gbu='git branch -u'
alias gc='git commit'
alias gca='git commit --amend'
alias gcm='git commit -m'
alias gcp='git cherry-pick'
alias gd='git diff'
alias gl='git log --graph --decorate'
alias gll='git log --oneline --decorate'
alias go='git checkout'
alias gob='git checkout -b'
alias gp='git pull'
alias gpr='git pull --rebase'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias gs='git status'
alias gst='git stash'
alias gsta='git stash apply'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gu='git branch -vv'
